#ifndef VCDRIVERS_DEFAULT_CONFIG_H
#define VCDRIVERS_DEFAULT_CONFIG_H

#ifndef VCDRIVERS_CONFIG_STDIOBASE_UART_DEV
#define VCDRIVERS_CONFIG_STDIOBASE_UART_DEV UART_DEV(1)
#endif

#endif /* VCDRIVERS_DEFAULT_CONFIG_H */
